### get all users
GET http://localhost:3000/users

###

GET http://localhost:3000/users/1

### create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "fullName":"Peter Njoroge",
  "email": "peter@gmail.com",
  "phoneNumber": "+254712345678",
  "nationalId": "12345678",
  "password": "StrongPass@123"
}

###
X-Http-Method-Override: 
PUT http://localhost:3000/songs/1

###

DELETE http://localhost:3000/songs/1